import { StyleSheet } from "react-native";
import { Colors, Fonts, Sizes } from "../../constants/Layout";

export const detailStyle = StyleSheet.create({
  backBtnCont: {
    zIndex: 999,
    padding: 3,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 7,
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "180deg" }],
    marginTop: -45,
    marginLeft: 18,
  },
  cartsBtnCont: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 20,
    zIndex: 2222,
  },
  viewCartsBent: {
    backgroundColor: Colors.primary,
    width: "80%",
    alignSelf: "center",
    padding: 7,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    elevation: 2,
  },
  viewBtnText: {
    color: Colors.warmWhite,
    textAlign: "center",
    ...Fonts.body2,
    fontSize: 18,
  },
  main: {
    flex: 1,
    height: Sizes.height,
    width: Sizes.width,
  },
  imageCont: {
    flex: 0.45,
    backgroundColor: Colors.primary,
  },
  contentCont: {
    backgroundColor: Colors.warmWhite,
    borderTopLeftRadius: 30,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: Sizes.height / 1.7,
    borderTopRightRadius: 30,
    elevation: 6,
    paddingLeft: 15,
    paddingRight: 15,
  },
  headerCont: {
    marginTop: 20,
    paddingLeft: 15,
  },
  itemName: {
    ...Fonts.h3,
    color: Colors.darkgray,
    marginTop: -10,
  },
  addCartBtn: {
    backgroundColor: Colors.primary,
    padding: 5,
    borderRadius: 5,
    paddingLeft: 20,
    borderTopLeftRadius: 35,
  },
  addText: {
    color: Colors.white,
    ...Fonts.body3,
  },
  price: {
    ...Fonts.h1,
    marginTop: 5,
    color: Colors.darkgray,
  },
  ingredientCont: {
    borderColor: Colors.deepDarkGray,
    flexDirection: "row",
    flexWrap: "wrap",
    paddingBottom: 10,
    borderBottomWidth: 0.2,
  },
  ingText: {
    backgroundColor: Colors.white,
    borderRadius: 6,
    ...Fonts.body3,
    marginTop: 7,
    elevation: 2,
    padding: 5,
    marginRight: 4,
  },
  likeText: {
    ...Fonts.style2,
    color: Colors.deepDarkGray,
    marginTop: 10,
  },
  imgCont: {
    alignSelf: "center",
    height: 170,
    width: 170,
    marginTop: -30,
    position: "absolute",
    zIndex: 999,
  },
  logoImg: {
    position: "absolute",
    alignSelf: "center",
    top: 80,
    zIndex: 333,
  },
  priceCont: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    paddingLeft: 15,
    alignItems: "center",
  },
  counterCont: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  counterBtn: {
    marginLeft: 6,
    marginRight: 6,
  },
  counterNum: {
    ...Fonts.h2,
    color: "#f10246",
  },
  addCarts: {
    flexDirection: "row",
    width: "93%",
    alignSelf: "center",
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginTop: 15,
  },
  cartsText: {
    ...Fonts.h3,
    color: Colors.white,
    textTransform: "uppercase",
    marginLeft: 20,
  },
  mayLikeCont: {
    paddingLeft: 15,
    paddingTop: 10,
  },
  maylikeText: {
    ...Fonts.h3,
    fontSize: 15,
    textTransform: "uppercase",
  },
  statusbar: {
    backgroundColor: "#f51b37",
    position: "absolute",
    top: 0,
    height: 24,
    left: 0,
    right: 0,
    zIndex: 999,
  },
});
